#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Decrease key repeat delay to 300ms and increase key repeat rate to 50 per second.
xset r rate 300 50
# Map the caps lock key to super, and map the menu key to right super.
#setxkbmap -option ctrl:nocaps,ctrl:lctrl_meta,compose:menu
# When caps lock is pressed only once, treat it as escape.
#killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
# Turn off caps lock if on since there is no longer a key for it.
#xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock
xmodmap ${XDG_CONFIG_HOME}/x11/xmodmap

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="mpd xcompmgr dunst unclutter pipewire blueman-applet"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

syncthing --no-browser &
emacs --daemon &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
